// src/utils/continent-mapper.ts

export class ContinentMapper {
  private static readonly map: Record<string, string> = {
    AFG: 'Asia',
    ALB: 'Europe',
    DZA: 'Africa',
    ASM: 'Oceania',
    AND: 'Europe',
    AGO: 'Africa',
    AIA: 'North America',
    ATA: 'Antarctica',
    ATG: 'North America',
    ARG: 'South America',
    ARM: 'Asia',
    ABW: 'North America',
    AUS: 'Oceania',
    AUT: 'Europe',
    AZE: 'Asia',
    BHS: 'North America',
    BHR: 'Asia',
    BGD: 'Asia',
    BRB: 'North America',
    BLR: 'Europe',
    BEL: 'Europe',
    BLZ: 'North America',
    BEN: 'Africa',
    BMU: 'North America',
    BTN: 'Asia',
    BOL: 'South America',
    BES: 'North America',
    BIH: 'Europe',
    BWA: 'Africa',
    BRA: 'South America',
    IOT: 'Asia',
    BRN: 'Asia',
    BGR: 'Europe',
    BFA: 'Africa',
    BDI: 'Africa',
    KHM: 'Asia',
    CMR: 'Africa',
    CAN: 'North America',
    CPV: 'Africa',
    CYM: 'North America',
    CAF: 'Africa',
    TCD: 'Africa',
    CHL: 'South America',
    CHN: 'Asia',
    CXR: 'Asia',
    CCK: 'Asia',
    COL: 'South America',
    COM: 'Africa',
    COG: 'Africa',
    COD: 'Africa',
    COK: 'Oceania',
    CRI: 'North America',
    HRV: 'Europe',
    CUB: 'North America',
    CUW: 'North America',
    CYP: 'Asia',
    CZE: 'Europe',
    DNK: 'Europe',
    DJI: 'Africa',
    DMA: 'North America',
    DOM: 'North America',
    ECU: 'South America',
    EGY: 'Africa',
    SLV: 'North America',
    GNQ: 'Africa',
    ERI: 'Africa',
    EST: 'Europe',
    ETH: 'Africa',
    FLK: 'South America',
    FRO: 'Europe',
    FJI: 'Oceania',
    FIN: 'Europe',
    FRA: 'Europe',
    GUF: 'South America',
    PYF: 'Oceania',
    GAB: 'Africa',
    GMB: 'Africa',
    GEO: 'Asia',
    DEU: 'Europe',
    GHA: 'Africa',
    GIB: 'Europe',
    GRC: 'Europe',
    GRL: 'North America',
    GRD: 'North America',
    GLP: 'North America',
    GUM: 'Oceania',
    GTM: 'North America',
    GGY: 'Europe',
    GIN: 'Africa',
    GNB: 'Africa',
    GUY: 'South America',
    HTI: 'North America',
    VAT: 'Europe',
    HND: 'North America',
    HKG: 'Asia',
    HUN: 'Europe',
    ISL: 'Europe',
    IND: 'Asia',
    IDN: 'Asia',
    IRN: 'Asia',
    IRQ: 'Asia',
    IRL: 'Europe',
    IMN: 'Europe',
    ISR: 'Asia',
    ITA: 'Europe',
    CIV: 'Africa',
    JAM: 'North America',
    JPN: 'Asia',
    JEY: 'Europe',
    JOR: 'Asia',
    KAZ: 'Asia',
    KEN: 'Africa',
    KIR: 'Oceania',
    KOR: 'Asia',
    KWT: 'Asia',
    KGZ: 'Asia',
    PRK: 'Asia',
    LAO: 'Asia',
    LVA: 'Europe',
    LBN: 'Asia',
    LSO: 'Africa',
    LBR: 'Africa',
    LBY: 'Africa',
    LIE: 'Europe',
    LTU: 'Europe',
    LUX: 'Europe',
    MAC: 'Asia',
    MKD: 'Europe',
    MDG: 'Africa',
    MWI: 'Africa',
    MYS: 'Asia',
    MDV: 'Asia',
    MLI: 'Africa',
    MLT: 'Europe',
    MHL: 'Oceania',
    MTQ: 'North America',
    MRT: 'Africa',
    MUS: 'Africa',
    MYT: 'Africa',
    MEX: 'North America',
    FSM: 'Oceania',
    MDA: 'Europe',
    MCO: 'Europe',
    MNG: 'Asia',
    MNE: 'Europe',
    MSR: 'North America',
    MAR: 'Africa',
    MOZ: 'Africa',
    MMR: 'Asia',
    NAM: 'Africa',
    NRU: 'Oceania',
    NPL: 'Asia',
    NLD: 'Europe',
    NCL: 'Oceania',
    NZL: 'Oceania',
    NIC: 'North America',
    NER: 'Africa',
    NGA: 'Africa',
    NIU: 'Oceania',
    NFK: 'Oceania',
    MNP: 'Oceania',
    NOR: 'Europe',
    OMN: 'Asia',
    PAK: 'Asia',
    PLW: 'Oceania',
    PSE: 'Asia',
    PAN: 'North America',
    PNG: 'Oceania',
    PRY: 'South America',
    PER: 'South America',
    PHL: 'Asia',
    PCN: 'Oceania',
    POL: 'Europe',
    PRT: 'Europe',
    PRI: 'North America',
    QAT: 'Asia',
    REU: 'Africa',
    ROU: 'Europe',
    RUS: 'Europe',
    RWA: 'Africa',
    BLM: 'North America',
    SHN: 'Africa',
    KNA: 'North America',
    LCA: 'North America',
    MAF: 'North America',
    SPM: 'North America',
    VCT: 'North America',
    WSM: 'Oceania',
    SMR: 'Europe',
    STP: 'Africa',
    SAU: 'Asia',
    SEN: 'Africa',
    SRB: 'Europe',
    SYC: 'Africa',
    SLE: 'Africa',
    SGP: 'Asia',
    SXM: 'North America',
    SVK: 'Europe',
    SVN: 'Europe',
    SLB: 'Oceania',
    SOM: 'Africa',
    ZAF: 'Africa',
    SGS: 'Antarctica',
    SSD: 'Africa',
    ESP: 'Europe',
    LKA: 'Asia',
    SDN: 'Africa',
    SUR: 'South America',
    SWZ: 'Africa',
    SWE: 'Europe',
    CHE: 'Europe',
    SYR: 'Asia',
    TWN: 'Asia',
    TJK: 'Asia',
    TZA: 'Africa',
    THA: 'Asia',
    TLS: 'Asia',
    TGO: 'Africa',
    TKL: 'Oceania',
    TON: 'Oceania',
    TTO: 'North America',
    TUN: 'Africa',
    TUR: 'Asia',
    TKM: 'Asia',
    TCA: 'North America',
    TUV: 'Oceania',
    UGA: 'Africa',
    UKR: 'Europe',
    ARE: 'Asia',
    GBR: 'Europe',
    USA: 'North America',
    URY: 'South America',
    UZB: 'Asia',
    VUT: 'Oceania',
    VEN: 'South America',
    VNM: 'Asia',
    VGB: 'North America',
    VIR: 'North America',
    ESH: 'Africa',
    YEM: 'Asia',
    ZMB: 'Africa',
    ZWE: 'Africa',
  };

  public static getContinent(iso3: string): string {
    return this.map[iso3.toUpperCase()] || 'Unknown';
  }
}
