dependencies:
  - changed-files:
      - any-glob-to-any-file:
          - '**/package.json'
          - '**/package-lock.json'
          - '**/pyproject.toml'
          - '**/build.gradle'
          - '**/build.gradle.kts'
          - '**/pom.xml'

github-actions:
  - changed-files:
      - any-glob-to-any-file:
          - '.github/workflows/*.yml'
          - '.github/*.yml'

ci:
  - changed-files:
      - any-glob-to-any-file:
          - '.github/**'
          - 'devtools/**'

docs:
  - changed-files:
      - any-glob-to-any-file:
          - '**/*.md'

frontend:
  - changed-files:
      - any-glob-to-any-file:
          - 'src/**'
