import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "@smastrom/react-rating/style.css";
import Provider from "./Provider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
        <Provider>{children}</Provider>
  );
}
