name: 🔐 Security Vulnerability
description: Vertrauliche Meldung einer Sicherheitslücke im Profil-Modul oder anderen Omnixys-Services
labels: [security, confidential]
body:
  - type: markdown
    attributes:
      value: |
        ⚠️ **WICHTIG:** Bitte keine sensiblen Details öffentlich posten.
        Du kannst diese Vorlage ausfüllen und direkt an [security@omnixys.com](mailto:security@omnixys.com) senden oder als Issue erstellen (nur das Core-Team sieht Details).

  - type: input
    id: title
    attributes:
      label: Betroffener Bereich / Titel
      placeholder: z. B. "Fehlende Authentifizierung bei Profil-Update"
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Beschreibung des Problems
      description: Beschreibe die Sicherheitslücke möglichst genau.
      placeholder: |
        - Unautorisierter Zugriff auf Profil-Update-Endpunkt möglich
        - Kein Token erforderlich, um bestimmte Daten zu ändern
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Schritte zur Reproduktion
      description: Wie lässt sich das Verhalten nachvollziehen? (optional)
      render: shell
    validations:
      required: false

  - type: dropdown
    id: severity
    attributes:
      label: CVSS-Schweregrad (falls bekannt)
      options:
        - Critical (CVSS 9.0–10)
        - High (CVSS 7.0–8.9)
        - Medium (CVSS 4.0–6.9)
        - Low (CVSS 0.1–3.9)
        - Unklar
