// app/layout.tsx (RootLayout)
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";

import AppSidebar from "./components/AppSidebar";
import Navbar from "./components/Navbar";
import { SidebarProvider } from "./components/ui/sidebar";
import { cookies } from "next/headers";
import Box from "@mui/material/Box";
import { ThemeProvider } from "./providers/ThemeProvider";

const geistSans = Geist({ variable: "--font-geist-sans", subsets: ["latin"] });
const geistMono = Geist_Mono({ variable: "--font-geist-mono", subsets: ["latin"] });

export const metadata: Metadata = {
  title: "ShadCN Tutorial",
  description: "Generated by create next app",
};

export default async function AdminLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  const cookieStore = await cookies();
  const defaultOpen = cookieStore.get("sidebar_state")?.value === "true";

  return (
    // <Box lang="en" suppressHydrationWarning>
    //   <Box className={`${geistSans.variable} ${geistMono.variable}`}>
    <ThemeProvider>

      <SidebarProvider defaultOpen={defaultOpen}>
            <Box sx={{ display: "flex", minHeight: "100dvh" }}>
              <AppSidebar />
              <Box component="main" sx={{ flex: 1, display: "flex", flexDirection: "column" }}>
                <Navbar />
                <Box sx={{ px: 2 }}>{children}</Box>
              </Box>
            </Box>
          </SidebarProvider>
        </ThemeProvider>
    //   </Box>
    // </Box>
  );
}
